"""quality module - inspections and defects

Revision ID: 0012
Revises: 0011
Create Date: 2026-08-29
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Quality Inspection Status enum
    inspection_status = postgresql.ENUM('draft', 'in_progress', 'completed', 'cancelled', 
                                         name='inspectionstatus', create_type=False)
    inspection_status.create(op.get_bind(), checkfirst=True)
    
    # Defect Severity enum
    defect_severity = postgresql.ENUM('critical', 'major', 'minor', 'cosmetic', 
                                       name='defectseverity', create_type=False)
    defect_severity.create(op.get_bind(), checkfirst=True)
    
    # Defect Status enum
    defect_status = postgresql.ENUM('open', 'investigating', 'resolved', 'closed', 
                                     name='defectstatus', create_type=False)
    defect_status.create(op.get_bind(), checkfirst=True)

    # quality_inspections table
    op.create_table(
        'quality_inspections',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('inspection_number', sa.String(30), nullable=False),
        sa.Column('name', sa.String(200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('inspection_type', sa.String(50), nullable=False, server_default='incoming'),
        sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', 'cancelled', 
                  name='inspectionstatus'), nullable=False, server_default='draft'),
        sa.Column('item_id', sa.Integer(), sa.ForeignKey('inventory_items.id', ondelete='SET NULL'), nullable=True),
        sa.Column('batch_number', sa.String(100), nullable=True),
        sa.Column('supplier_id', sa.Integer(), sa.ForeignKey('vendors.id', ondelete='SET NULL'), nullable=True),
        sa.Column('quantity_inspected', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('quantity_passed', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('quantity_failed', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('pass_rate', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('inspector_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('inspection_number'),
    )
    op.create_index('ix_quality_inspections_status', 'quality_inspections', ['status'])
    op.create_index('ix_quality_inspections_type', 'quality_inspections', ['inspection_type'])
    op.create_index('ix_quality_inspections_created_at', 'quality_inspections', ['created_at'])
    op.create_index('ix_quality_inspections_inspection_number', 'quality_inspections', ['inspection_number'])

    # quality_defects table
    op.create_table(
        'quality_defects',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('inspection_id', sa.Integer(), sa.ForeignKey('quality_inspections.id', ondelete='CASCADE'), nullable=False),
        sa.Column('defect_type', sa.String(100), nullable=False),
        sa.Column('severity', sa.Enum('critical', 'major', 'minor', 'cosmetic', 
                  name='defectseverity'), nullable=False, server_default='minor'),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('quantity_affected', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('root_cause', sa.Text(), nullable=True),
        sa.Column('corrective_action', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('open', 'investigating', 'resolved', 'closed', 
                  name='defectstatus'), nullable=False, server_default='open'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_quality_defects_status', 'quality_defects', ['status'])
    op.create_index('ix_quality_defects_severity', 'quality_defects', ['severity'])
    op.create_index('ix_quality_defects_created_at', 'quality_defects', ['created_at'])
    op.create_index('ix_quality_defects_inspection_id', 'quality_defects', ['inspection_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_defects')
    op.drop_table('quality_inspections')
    
    # Drop enums
    op.execute('DROP TYPE IF EXISTS defectstatus')
    op.execute('DROP TYPE IF EXISTS defectseverity')
    op.execute('DROP TYPE IF EXISTS inspectionstatus')
    # ### end Alembic commands ###
