"""tasks module - project tasks and comments

Revision ID: 0013
Revises: 0012
Create Date: 2026-08-29
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Task Priority enum
    task_priority = postgresql.ENUM('low', 'medium', 'high', 'urgent', 
                                     name='taskpriority', create_type=False)
    task_priority.create(op.get_bind(), checkfirst=True)
    
    # Task Status enum
    task_status = postgresql.ENUM('pending', 'in_progress', 'completed', 'cancelled', 'blocked', 
                                   name='taskstatus', create_type=False)
    task_status.create(op.get_bind(), checkfirst=True)

    # project_tasks table
    op.create_table(
        'project_tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(300), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', 'blocked', 
                  name='taskstatus'), nullable=False, server_default='pending'),
        sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', 
                  name='taskpriority'), nullable=False, server_default='medium'),
        sa.Column('assigned_to_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('parent_task_id', sa.Integer(), sa.ForeignKey('project_tasks.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_by_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_project_tasks_status', 'project_tasks', ['status'])
    op.create_index('ix_project_tasks_priority', 'project_tasks', ['priority'])
    op.create_index('ix_project_tasks_assigned_to_id', 'project_tasks', ['assigned_to_id'])
    op.create_index('ix_project_tasks_created_by_id', 'project_tasks', ['created_by_id'])

    # task_comments table
    op.create_table(
        'task_comments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('task_id', sa.Integer(), sa.ForeignKey('project_tasks.id', ondelete='CASCADE'), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_by_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_task_comments_task_id', 'task_comments', ['task_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_comments')
    op.drop_table('project_tasks')
    
    # Drop enums
    op.execute('DROP TYPE IF EXISTS taskstatus')
    op.execute('DROP TYPE IF EXISTS taskpriority')
    # ### end Alembic commands ###
